=== DejanUrosevic/XML-Projekat/HelloWeb01/HelloWeb/data/xsd/clan.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.parlament.gov.rs/clan" xmlns:clan="http://www.parlament.gov.rs/clan">

    <xs:element name="Clan">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" name="Opis" type="xs:string"/>
                <xs:element name="Naziv" type="xs:string"/>
                <xs:element name="Sadrzaj">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element minOccurs="0" name="Stav" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Redni_broj" type="xs:long"/>
                                        <xs:element name="IDPropisa" type="xs:positiveInteger"/>
                                        <xs:element name="NazivPropisa" type="xs:string"/>
                                        <xs:element name="IDClana" type="xs:positiveInteger"/>
                                        <xs:element name="NazivClana" type="xs:string"/>
                                        <xs:element name="Tekst" type="xs:string"
                                            maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element minOccurs="0" name="Tekst" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" name="text"
                                            type="xs:string"/>
                                        <xs:element maxOccurs="1" minOccurs="0" name="IDPropisa"
                                            type="xs:positiveInteger"/>
                                        <xs:element maxOccurs="1" minOccurs="0" name="NazivPropisa"
                                            type="xs:string"/>
                                        <xs:element maxOccurs="1" minOccurs="0" name="IDClana"
                                            type="xs:positiveInteger"/>
                                        <xs:element maxOccurs="1" minOccurs="0" name="NazivClana"
                                            type="xs:string"/>
                                        <xs:element maxOccurs="unbounded" minOccurs="0"
                                            name="RedniBrojStava" type="xs:long"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="ID" type="xs:positiveInteger" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== DejanUrosevic/XML-Projekat/HelloWeb01/HelloWeb/data/xsd/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Clan xmlns="http://www.parlament.gov.rs/clan"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.parlament.gov.rs/clan file:/D:/4.%20godina/XML/app/HelloWeb01/HelloWeb/data/xsd/clan.xsd" ID="1582105513">
    <Opis>Opis clana</Opis>
    <Naziv>Clan br. 1</Naziv>
    <Sadrzaj>
        <Stav>Stav br. 1</Stav>
        <Tekst>
            <Clan ID="1572382299">
                <Opis>Opis unutrasnjeg clana</Opis>
                <Naziv>Naziv unutrasnjeg clana</Naziv>
                <Sadrzaj>
                    <Tekst>Samo obican tekst
                    </Tekst>
                    <Stav>Stav br. 2</Stav>
                    <Tekst>
                    </Tekst>
                </Sadrzaj>
            </Clan>
        </Tekst>
        <Stav>Stab br. 3</Stav>
    </Sadrzaj>
</Clan>
